modLoader="javafml"
loaderVersion="[47,)"
license="MPL-2.0"

[[mods]]
modId="cloudsolutions_testmod"
version="1.0"
displayName="CloudSolutions Testmod"
description="CloudSolutions peripheral GameTests."

[[dependencies.cloudsolutions_testmod]]
modId="cloudsolutions"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
