modLoader="kotlinforforge"
loaderVersion="[4,)"

issueTrackerURL="https://github.com/SirEdvin/DataFortress/issues"
logoFile="pack.png"

license="MIT"

[[mods]]
modId="datafortress"
version="${file.jarVersion}"
displayName="Data Fortress"
displayURL="https://github.com/SirEdvin/DataFortress"

credits=""
authors="SirEdvin"
description='''
A little crazy CC:T addon that stores different data and, well, share it via internal http server!
'''

[[dependencies.datafortress]]
modId="forge"
mandatory=true
versionRange="[${forgeVersion},48)"
ordering="NONE"
side="BOTH"

[[dependencies.datafortress]]
modId="computercraft"
mandatory=true
versionRange="[${computercraftVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.datafortress]]
modId="peripheralium"
mandatory=true
versionRange="[${peripheraliumVersion},)"
ordering="NONE"
side="BOTH"