modLoader="kotlinforforge"
loaderVersion="[4,)"

issueTrackerURL="https://github.com/SirEdvin/TemplateProject/issues"
logoFile="pack.png"

license="MIT"

[[mods]]
modId="template"
version="${file.jarVersion}"
displayName="Template"
displayURL="https://github.com/SirEdvin/TemplateProject/"

credits=""
authors=""
description='''
'''

[[dependencies.template]]
modId="forge"
mandatory=true
versionRange="[${forgeVersion},48)"
ordering="NONE"
side="BOTH"

[[dependencies.template]]
modId="computercraft"
mandatory=true
versionRange="[${computercraftVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.template]]
modId="peripheralium"
mandatory=true
versionRange="[${peripheraliumVersion},)"
ordering="NONE"
side="BOTH"