modLoader="kotlinforforge"
loaderVersion="[4,)"

issueTrackerURL="https://github.com/SirEdvin/CloudSolutions/issues"
logoFile="pack.png"

license="MIT"

[[mods]]
modId="cloudsolutions"
version="${file.jarVersion}"
displayName="Cloud Solutions"
displayURL="https://github.com/SirEdvin/CloudSolutions"

credits=""
authors="SirEdvin"
description='''
A little crazy CC:T addon that stores different data and, well, share it via internal http server!
'''

[[dependencies.cloudsolutions]]
modId="forge"
mandatory=true
versionRange="[${forgeVersion},48)"
ordering="NONE"
side="BOTH"

[[dependencies.cloudsolutions]]
modId="computercraft"
mandatory=true
versionRange="[${computercraftVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.cloudsolutions]]
modId="peripheralium"
mandatory=true
versionRange="[${peripheraliumVersion},)"
ordering="NONE"
side="BOTH"