modLoader="kotlinforforge"
loaderVersion="[5,)"
license="MIT"
issueTrackerURL="https://github.com/SirEdvin/CloudSolutions/issues"

[[mods]]
modId="cloudsolutions"
version="${file.jarVersion}"
displayName="Cloud Solutions"
displayURL="https://github.com/SirEdvin/CloudSolutions"
logoFile="pack.png"
authors="SirEdvin"
description='''
A little crazy CC:T addon that stores different data and, well, share it via internal http server!
'''

[[dependencies.cloudsolutions]]
modId="neoforge"
type="required"
versionRange="[${neoforgeVersion},21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.cloudsolutions]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.cloudsolutions]]
modId="computercraft"
type="required"
versionRange="[${computercraftVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.cloudsolutions]]
modId="tweakium"
type="required"
versionRange="[${tweakiumVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.cloudsolutions]]
modId="broccolium"
type="required"
versionRange="[${broccoliumVersion},)"
ordering="NONE"
side="BOTH"
